image: nova.registry.c1.io:5000/ubuntu
services:
  - c12e/mongodb
script:
  - env |grep -i mongo
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
  - sudo apt-get update
  - sudo apt-get install mongodb-10gen
  - sleep 500
  - mongo $MONGODB_PORT_27017_TCP_ADDR:$MONGODB_PORT_27017_TCP_PORT
  - sleep 120
